[phases.setup]
runtime = "python-3.10.12"

[phases.setup.aptPkgs]
packages = [
  "ffmpeg",
  "libavformat-dev",
  "libavcodec-dev",
  "libavdevice-dev",
  "libavutil-dev",
  "libavfilter-dev",
  "libswscale-dev",
  "libswresample-dev",
  "pkg-config",
  "build-essential",
  "python3-dev",
  "cython3"
]
