[phases.setup]
aptPkgs = [
  "ffmpeg",
  "libavformat-dev",
  "libavcodec-dev",
  "libavdevice-dev",
  "libavutil-dev",
  "libavfilter-dev",
  "libswscale-dev",
  "libswresample-dev",
  "pkg-config",
  "build-essential",
  "python3-dev",
  "cython3"
]
